### ISSUE TITLE
error upgrading to Rails 3.2

### ISSUE THREAD

**Issue by dgilperez** [nesquena/query_reviewer#14]
Hi!

I'm upgrading my rails 3.1 app to 3.2. I have been experiencing some weirdness I believe related to the query_reviewer

```
   (0.2ms)  SET PROFILING=1
  Measurement Load (0.8ms)  SELECT SQL_NO_CACHE `houses`.* FROM `houses` INNER JOIN `lanes` ON `lanes`.`id` = `houses`.`variable_id` WHERE `lanes`.`name` = 'weight' AND `houses`.`user_id` = 23 ORDER BY date DESC LIMIT 1
  EXPLAIN (25.5ms)  EXPLAIN SET PROFILING=1
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET PROFILING=1' at line 1: EXPLAIN SET PROFILING=1
Completed 500 Internal Server Error in 803ms

```

It seems Rails is confusing the query that has to EXPLAIN. This happens with many slow queries and works good with Rails 3.1 or by removing query_reviewer in Rails 3.2.

I use `query_reviewer`a lot and find it really helpful, so any ideas will be appreciated! 

thanks for the effort put into this,

David

**Comment by andoq** [comment]
Rails 3.2 is trying to auto explain statements in 3.2.  With Query Reviewer, you don't need this.  I wasn't sure how to disable this, so I set the threshold very high.  In development.rb:

config.active_record.auto_explain_threshold_in_seconds = 15

that's 15 seconds, and seems to have solved this issue for me.

**Comment by dgilperez** [comment]
That's good enough, thank you very much !

I'm experiencing more issues that seem to be related to Devise 2.0.4 on Rails 3.2.2, I'll open a new issue.
