### ISSUE TITLE
the configuration file isn't being found and is always using query_reviewer_defaults.yml

### ISSUE THREAD

**Issue by varchar** [nesquena/query_reviewer#2]
the configuration file isn't being found and is always using query_reviewer_defaults.yml
Rails.root is returning '' when the app starts up and thats keeping the proper config file from loading

Here is my output from the debugger:

Pairing3:ip 0 [03-01 18:57](develop)~/Dev/health-teams 
! rails s --debugger
DEPRECATION WARNING: railtie_name is deprecated and has no effect. (called from <top (required)> at /Users/ip/Dev/health-teams/config/application.rb:7)
[13, 22] in /Users/ip/.rvm/gems/ruby-1.9.2-p0@health_teams/bundler/gems/query_reviewer-726684eccc25/lib/query_reviewer.rb
   13      CONFIGURATION.merge!(default_config[Rails.env || "test"] || {})
   14  
   15      app_config_file = File.join(Rails.root.to_s, "config", "query_reviewer.yml")
   16      require 'ruby-debug'
   17      debugger
=> 18      if File.exist?(app_config_file)
   19        app_config = YAML.load(ERB.new(IO.read(app_config_file)).result)
   20        CONFIGURATION.merge!(app_config["all"] || {})
   21        CONFIGURATION.merge!(app_config[Rails.env || "test"] || {})
   22      end
/Users/ip/.rvm/gems/ruby-1.9.2-p0@health_teams/bundler/gems/query_reviewer-726684eccc25/lib/query_reviewer.rb:18
if File.exist?(app_config_file)
(rdb:1) app_config_file
"/config/query_reviewer.yml"
(rdb:1) Rails.env
"development"
(rdb:1) Rails.root
nil
(rdb:1)

**Comment by nesquena** [comment]
Thanks for the report, I will take a look.

**Comment by nesquena** [comment]
This is on Rails 3?

**Comment by be9** [comment]
Came up with the pull request #3 here

**Comment by nesquena** [comment]
Thanks, merged in and pushed a new release

**Comment by varchar** [comment]
Thanks!  this worked great
