### ISSUE TITLE
in rails 3.2.5 project no display on 1st request bc cookie not set, which means no ability to SET cookie

### ISSUE THREAD

**Issue by TJamesCorcoran** [nesquena/query_reviewer#24]
I've used query_reviewer in a 2.3.5 environment and have ported my project to rails 3.2.5.

When I restart 'thin' and load a page, I don't get any view injected by query_review.  I debugged the problem and file
   gems/query_reviewer-0.1.6/lib/query_reviewer/controller_extensions.rb
def
  add_query_output_to_view(total_time)
is returning on the first line
  return unless Thread.current["query_reviewer_enabled"]

which is set to false because in the same file, in method
   perform_action_with_query_review(*args)

the first line is setting Thread.current["query_reviewer_enabled"] false because while  
     CONFIGURATION["enabled"] = true 
unfortunately 
   cookies["query_review_enabled"] = false

How do I set the cookie true?  By having the view injected and clicking the "on" button...but it's a catch-22 because the on button isn't present.

I've worked around this by adding a line to force the display, but what's the right thing?

---

My config looks like this:
all:
    inject_view: true
    stack_trace_lines: 3
    trace_includes_vendor: false
    trace_includes_lib: true
    profiling: enabled
    production_data: true
    max_safe_key_length: 100
    disable_sql_cache: true    

```
warn_severity: 3
critical_severity: 7

warn_select_count: 20
critical_select_count: 50

warn_update_count: 5
critical_update_count: 10

warn_insert_count: 5
critical_insert_count: 10

warn_delete_count: 5
critical_delete_count: 10

warn_duration_threshold: 0.2
critical_duration_threshold: 1.0

warn_affected_rows: 10
critical_affected_rows: 100
```

development:
    enabled: true

production:
    enabled: false

test:
    enabled: false

**Comment by nesquena** [comment]
Can you try query_reviewer off git after this request https://github.com/nesquena/query_reviewer/pull/20 and see if it resolves this issue?

**Comment by TJamesCorcoran** [comment]
That worked for me - thanks!

...and thanks for your work on this project.  It's VERY useful to me, and I appreciate that you've shared this w the world!

**Comment by nesquena** [comment]
No problem, glad it worked
