### ISSUE TITLE
Deprecation warnings with recent rubygems versions

### ISSUE THREAD

**Issue by phiggins** [nesquena/query_reviewer#5]
Using query_reviewer with recent versions of rubygems prints warnings like this:

```
NOTE: Gem.searcher is deprecated, use Specification. It will be removed on or after 2011-11-01.
Gem.searcher called from XXXXXX/bundler/gems/query_reviewer-9de60e75d180/lib/query_reviewer.rb:25.
NOTE: Gem::GemPathSearcher#initialize is deprecated with no replacement. It will be removed on or after 2011-10-01.
Gem::GemPathSearcher#initialize called from XXXXXX/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems.rb:952.
NOTE: Gem::GemPathSearcher#find is deprecated with no replacement. It will be removed on or after 2011-10-01.
Gem::GemPathSearcher#find called from XXXXXX/bundler/gems/query_reviewer-9de60e75d180/lib/query_reviewer.rb:25.
```

**Comment by nesquena** [comment]
Yep its from this line https://github.com/nesquena/query_reviewer/blob/master/lib/query_reviewer.rb#L25 Seems like according to this http://blog.segment7.net/2011/05/18/rubygems-deprecations we should switch to `Gem::Specification.find_by_path 'uv'`

**Comment by nesquena** [comment]
Fixed here: https://github.com/nesquena/query_reviewer/commit/c8f93dc70e55fdcb20d8902a590c54c6f45d7590 Anyone able to confirm this works OK?

**Comment by phiggins** [comment]
This appears to work for me with rubygems 1.8.10. Thanks for the quick response!

**Comment by nesquena** [comment]
Great, closing thanks!
