### ISSUE TITLE
Exception when saving data on Rails 3.1

### ISSUE THREAD

**Issue by erlingur** [nesquena/query_reviewer#9]
```
undefined method `gsub!' for #<Arel::InsertManager:0x007fd015e4c630>
```

Got this when running a create method on a model.

Full trace: https://gist.github.com/1307784

**Comment by nesquena** [comment]
This is with Rails 3.1. I actually have no 3.1 projects at the moment and I suspect the issue has to do with changes to the way queries are generated in that version. If anyone has a patch for compatibility, I will apply it ASAP assuming it maintains compatibility with 2.X and 3.
